entries:
- title: sidebar
  product: Shape Optimization Application
  output: web
  folders:
  - title: General
    output: web
    folderitems:
    - title: Overview
      url: /pages/Applications/Shape_Optimization_Application/General/Overview.html
      output: web
    - title: Application Structure
      url: /pages/Applications/Shape_Optimization_Application/General/Application_structure.html
      output: web
      subfolders:
      - title: Sensitivity Analysis
        output: web
        subfolderitems:
        - title: Adjoint approach
          url: /pages/Applications/Shape_Optimization_Application/General/Sensitivity_Analysis/Adjoint_approach.html
          output: web
        - title: Finite difference or direct approach
          url: /pages/Applications/Shape_Optimization_Application/General/Sensitivity_Analysis/Finite_difference_or_direct_approach.html
          output: web
  - title: Technologies
    output: web
    folderitems:
    - title: Objectives
      url: /pages/Applications/Shape_Optimization_Application/Technologies/Objectives.html
      output: web
    - title: Constraints
      url: /pages/Applications/Shape_Optimization_Application/Technologies/Constraints.html
      output: web
    - title: Vertex morphing
      url: /pages/Applications/Shape_Optimization_Application/Technologies/Vertex_morphing.html
      output: web
    - title: Damping
      url: /pages/Applications/Shape_Optimization_Application/Technologies/Damping.html
      output: web
      subfolders:
      - title: Algorithms
        output: web
        subfolderitems:
        - title: Steepest Descent
          url: /pages/Applications/Shape_Optimization_Application/Technologies/Algorithms/steepest_descent.html
          output: web
        - title: Penalized Projection
          url: /pages/Applications/Shape_Optimization_Application/Technologies/Algorithms/penalized_projection.html
          output: web
  - title: List of response functions
    output: web
    folderitems:
    - title: Average temperature
      url: /pages/Applications/Shape_Optimization_Application/List_of_response_functions/average_temperature.html
      output: web
    - title: Kreisselmeier aggregation
      url: /pages/Applications/Shape_Optimization_Application/List_of_response_functions/Kreisselmeier_aggregation.html
      output: web
    - title: Mass
      url: /pages/Applications/Shape_Optimization_Application/List_of_response_functions/Mass.html
      output: web
    - title: Strain energy
      url: /pages/Applications/Shape_Optimization_Application/List_of_response_functions/Strain_energy.html
      output: web
  - title: Siemens NX
    output: web
    folderitems:
    - title: Overview
      url: /pages/Applications/Shape_Optimization_Application/Siemens_NX/Overview.html
      output: web
    - title: Objectives and Constraints
      url: /pages/Applications/Shape_Optimization_Application/Siemens_NX/Objectives_and_constraints.html
      output: web
    - title: Design variables
      url: /pages/Applications/Shape_Optimization_Application/Siemens_NX/Design_variables.html
      output: web
    - title: Optimization Settings
      url: /pages/Applications/Shape_Optimization_Application/Siemens_NX/Optimization_settings.html
      output: web
    - title: Run optimization
      url: /pages/Applications/Shape_Optimization_Application/Siemens_NX/Run_optimization.html
      output: web
    - title: Import results
      url: /pages/Applications/Shape_Optimization_Application/Siemens_NX/Import_results.html
      output: web
    - title: Convergence plot
      url: /pages/Applications/Shape_Optimization_Application/Siemens_NX/Convergence_plot.html
      output: web
      subfolders:
      - title: Responses
        output: web
        subfolderitems:
        - title: Average Temperature
          url: /pages/Applications/Shape_Optimization_Application/Siemens_NX/Responses/average_temperature.html
          output: web
        - title: Kreisselmeier Aggregated Stress
          url: /pages/Applications/Shape_Optimization_Application/Siemens_NX/Responses/kreisselmeier_aggregated_stress.html
          output: web
        - title: Mass
          url: /pages/Applications/Shape_Optimization_Application/Siemens_NX/Responses/mass.html
          output: web
        - title: Strain Energy
          url: /pages/Applications/Shape_Optimization_Application/Siemens_NX/Responses/strain_energy.html
          output: web
      - title: Guided beam example
        output: web
        subfolderitems:
        - title: Fixed beam primal problem construction
          url: /pages/Applications/Shape_Optimization_Application/Siemens_NX/Guided_beam_example/Primal_problem_construction.html
          output: web
        - title: Fixed beam optimization problem construction
          url: /pages/Applications/Shape_Optimization_Application/Siemens_NX/Guided_beam_example/Optimization_problem_construction.html
          output: web
  - title: Examples
    output: web
    folderitems:
    - title: Strain Energy Minimization 3D Shell
      url: /pages/Applications/Shape_Optimization_Application/Examples/remote_Strain_Energy_Minimization_3D_Shell.html
      output: web
    - title: Shape Update Optimization Stanford Bunny
      url: /pages/Applications/Shape_Optimization_Application/Examples/remote_Shape_Update_Optimization_Stanford_Bunny.html
      output: web
