entries:
- title: sidebar
  product: Shape Optimization Application
  output: web
  folders:
  - title: General
    output: web
    folderitems:
    - title: Multi objective optimization
      url: /pages/Applications/Shape_Optimization_Application/General/Multi_objective_optimization.html
      output: web
    - title: Shape Optimization Application
      url: /pages/Applications/Shape_Optimization_Application/General/shape_optimization_application.html
      output: web
      subfolders:
      - title: Sensitivity Analysis
        output: web
        subfolderitems:
        - title: Adjoint approach
          url: /pages/Applications/Shape_Optimization_Application/General/Sensitivity_Analysis/Adjoint_approach.html
          output: web
        - title: Finite difference or direct approach
          url: /pages/Applications/Shape_Optimization_Application/General/Sensitivity_Analysis/Finite_difference_or_direct_approach.html
          output: web
  - title: Technologies
    output: web
    folderitems:
    - title: Objectives
      url: /pages/Applications/Shape_Optimization_Application/Technologies/Objectives.html
      output: web
    - title: Constraints
      url: /pages/Applications/Shape_Optimization_Application/Technologies/Constraints.html
      output: web
    - title: Vertex morphing
      url: /pages/Applications/Shape_Optimization_Application/Technologies/Vertex_morphing.html
      output: web
      subfolders:
      - title: Algorithms
        output: web
        subfolderitems:
        - title: Steepest Descent
          url: /pages/Applications/Shape_Optimization_Application/Technologies/Algorithms/steepest_descent.html
          output: web
        - title: Penalized Projection
          url: /pages/Applications/Shape_Optimization_Application/Technologies/Algorithms/penalized_projection.html
          output: web
        - title: Gradient Projection
          url: /pages/Applications/Shape_Optimization_Application/Technologies/Algorithms/gradient_projection.html
          output: web
  - title: Interfaces
    output: web
    folderitems:
    - title: Analyzer interface
      url: https://github.com/KratosMultiphysics/Kratos/blob/master/applications/ShapeOptimizationApplication/python_scripts/analyzers/analyzer_base.py
      output: web
    - title: Response function interface
      url: https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/python_scripts/response_functions/response_function_interface.py
      output: web
  - title: List of Response Functions
    output: web
    folderitems:
    - title: Angle of attack
      url: /pages/Applications/Shape_Optimization_Application/List of Response Functions/Angle_of_attack.html
      output: web
    - title: Face angle
      url: /pages/Applications/Shape_Optimization_Application/List of Response Functions/Face_angle.html
      output: web
    - title: Mesh based packaging
      url: /pages/Applications/Shape_Optimization_Application/List of Response Functions/Mesh_based_packaging.html
      output: web
    - title: Plane based packaging
      url: /pages/Applications/Shape_Optimization_Application/List of Response Functions/Plane_based_packaging.html
      output: web
    - title: Surface normal shape change
      url: /pages/Applications/Shape_Optimization_Application/List of Response Functions/Surface_normal_shape_change.html
      output: web
    - title: Total volume
      url: /pages/Applications/Shape_Optimization_Application/List of Response Functions/Total_volume.html
      output: web
  - title: Examples
    output: web
    folderitems:
    - title: Strain Energy Minimization 3D Shell
      url: /pages/Applications/Shape_Optimization_Application/Examples/remote_Strain_Energy_Minimization_3D_Shell.html
      output: web
    - title: Bead Optimization Plate
      url: /pages/Applications/Shape_Optimization_Application/Examples/remote_Bead_Optimization_Plate.html
      output: web
    - title: Multi Constraint Optimization 3D Hook
      url: /pages/Applications/Shape_Optimization_Application/Examples/remote_Multi_Constraint_Optimization_3D_Hook.html
      output: web
    - title: Shape Update Optimization Stanford Bunny
      url: /pages/Applications/Shape_Optimization_Application/Examples/remote_Shape_Update_Optimization_Stanford_Bunny.html
      output: web
  - title: Siemens NX
    output: web
    folderitems:
    - title: Overview
      url: /pages/Applications/Shape_Optimization_Application/Siemens NX/Overview.html
      output: web
    - title: Objectives and Constraints
      url: /pages/Applications/Shape_Optimization_Application/Siemens NX/Objectives_and_constraints.html
      output: web
    - title: Design variables
      url: /pages/Applications/Shape_Optimization_Application/Siemens NX/Design_variables.html
      output: web
    - title: Optimization settings
      url: /pages/Applications/Shape_Optimization_Application/Siemens NX/Optimization_settings.html
      output: web
    - title: Run optimization
      url: /pages/Applications/Shape_Optimization_Application/Siemens NX/Run_optimization.html
      output: web
    - title: Import results
      url: /pages/Applications/Shape_Optimization_Application/Siemens NX/Import_results.html
      output: web
    - title: Convergence plot
      url: /pages/Applications/Shape_Optimization_Application/Siemens NX/Convergence_plot.html
      output: web
      subfolders:
      - title: Responses
        output: web
        subfolderitems:
        - title: Average Temperature
          url: /pages/Applications/Shape_Optimization_Application/Siemens NX/Responses/average_temperature.html
          output: web
        - title: Kreisselmeier Aggregated Stress
          url: /pages/Applications/Shape_Optimization_Application/Siemens NX/Responses/kreisselmeier_aggregated_stress.html
          output: web
        - title: Mass
          url: /pages/Applications/Shape_Optimization_Application/Siemens NX/Responses/mass.html
          output: web
        - title: Strain Energy
          url: /pages/Applications/Shape_Optimization_Application/Siemens NX/Responses/strain_energy.html
          output: web
        - title: eigen frequency
          url: /pages/Applications/Shape_Optimization_Application/Siemens NX/Responses/eigen_frequency.html
          output: web
