entries:
- title: sidebar
  product: Statistics Application
  output: web
  folders:
  - title: General
    output: web
    folderitems:
    - title: Overview
      url: /pages/Applications/Statistics_Application/General/Overview.html
      output: web
  - title: Norm Methods
    output: web
    folderitems:
    - title: Overview
      url: /pages/Applications/Statistics_Application/Norm_Methods/Overview.html
      output: web
  - title: Statistical Methods
    output: web
    folderitems:
    - title: Distribution
      url: /pages/Applications/Statistics_Application/Statistical_Methods/Distribution.html
      output: web
    - title: Max
      url: /pages/Applications/Statistics_Application/Statistical_Methods/Max.html
      output: web
    - title: Mean
      url: /pages/Applications/Statistics_Application/Statistical_Methods/Mean.html
      output: web
    - title: Median
      url: /pages/Applications/Statistics_Application/Statistical_Methods/Median.html
      output: web
    - title: Min
      url: /pages/Applications/Statistics_Application/Statistical_Methods/Min.html
      output: web
    - title: Root Mean Square
      url: /pages/Applications/Statistics_Application/Statistical_Methods/Root_Mean_Square.html
      output: web
    - title: Sum
      url: /pages/Applications/Statistics_Application/Statistical_Methods/Sum.html
      output: web
    - title: Variance
      url: /pages/Applications/Statistics_Application/Statistical_Methods/Variance.html
      output: web
