name: Build Docker Images for CI
# this workflow creates the Docker-Images used in the Continuous Integration (CI)
# It intentionally creates all images, such that they are on the same state

on:
  push:
    branches:
      - 'master'
    paths:
      - 'scripts/docker_files/docker_file_ci_windows/*'
      - '.github/workflows/build_docker_images_for_ci_windows.yml'
  pull_request:
    branches:
      - 'master'
    paths:
      - 'scripts/docker_files/docker_file_ci_windows/*'
      - '.github/workflows/build_docker_images_for_ci_windows.yml'

jobs:
  build-docker-ubuntu:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file scripts/docker_files/docker_file_ci_windows/DockerFile --tag kratosmultiphysics/kratos-image-ci-windows
    - name: Docker Login
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Publish the Docker image
      if: ${{ github.event_name == 'push'}}
      # only push the new image when the changes are merged to master
      run: docker push kratosmultiphysics/kratos-image-ci-windows