name: Nightly Wheels Build and Test

on:
  pull_request:
    paths:
    - '.github/workflows/nightly_wheels_build_and_test.yml'
    - 'scripts/wheels/**'


  schedule:
    - cron:  '0 1 * * *'

  workflow_dispatch:

# for cancelling redundant runs
concurrency:
  group: nightly-wheels-build-test-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  linux-wheel:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2

    - name: Build
      shell: bash
      run: |
        mkdir ${GITHUB_WORKSPACE}/wheels
        docker run --rm -v ${GITHUB_WORKSPACE}/wheels:/data_swap_guest kratosmultiphysics/kratos-wheelbuilder-linux ${GITHUB_HEAD_REF}
        ls -al ${GITHUB_WORKSPACE}/wheels

    - name: Install
      shell: bash
      run: |
        python3 -m pip install --no-index --find-links=${GITHUB_WORKSPACE}/wheels/ KratosMultiphysics_all KratosSwimmingDEMApplication KratosMeshMovingApplication KratosShapeOptimizationApplication KratosCoSimulationApplication KratosMappingApplication KratosMultilevelMonteCarloApplication KratosStatisticsApplication KratosDelaunayMeshingApplication

    - name: Running small tests
      shell: bash
      run: |
        python3 kratos/python_scripts/run_tests.py -l small -c python3 -p "${GITHUB_WORKSPACE}/applications"
